name: build and push syncthing to docker hub

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release tag
        id: tag
        run: |
          export REMOTEVERSION=$(wget -qO- https://api.github.com/repos/linuxserver/docker-syncthing/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          echo "release_tag=${REMOTEVERSION}" >> $GITHUB_OUTPUT
          echo "release_tag_short=${REMOTEVERSION%%-*}" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/syncthing:latest , ${{ secrets.DOCKERHUB_USERNAME }}/syncthing:${{ steps.tag.outputs.release_tag }} , ${{ secrets.DOCKERHUB_USERNAME }}/syncthing:${{ steps.tag.outputs.release_tag_short }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 8